name: Setup Playwright
description: Install Playwright Chromium

runs:
  using: composite
  steps:
    - name: Install Playwright Chromium
      shell: bash
      run: pnpm exec playwright install chromium
