name: 🔎 Code Quality

on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  linter:
    name: 🧹 Linter
    if: github.event.pull_request.draft == false
    timeout-minutes: 10
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Run oxlint
        run: pnpm oxlint --deny-warnings .

  typescriptChecker:
    name: 🟦 TypeScript Checker
    if: github.event.pull_request.draft == false
    timeout-minutes: 10
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Run Typescript checker
        run: pnpm run lint:ts

  tests:
    name: 🔬 Tests
    if: github.event.pull_request.draft == false
    timeout-minutes: 10
    runs-on: self-hosted
    env:
      VITE_BASE_URL: http://localhost:3000
      VITE_S3_BUCKET_PUBLIC_URL: "http://localhost:9000/default"
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-
            ${{ runner.os }}-pnpm-store-
            ${{ runner.os }}-

      - name: Install deps
        run: pnpm install

      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright

      - name: Run tests
        run: SKIP_ENV_VALIDATION=true pnpm run test:ci
